### ISSUE TITLE
Phase 1: Project Planning and IT Requirements

### ISSUE THREAD

**Issue by f-allian** [RSE-Sheffield/SORTOnline#3]
- [x]  Gather requirements from stakeholder meeting on 09 July 2024

- [x] Review the [current iteration of the SORT tool](https://www.england.nhs.uk/publication/self-assessment-of-organisational-readiness-tool-sort-guide/) and understand current processes and workflows

- [x]  Identify the technology stack needed for this work (likely Django, PostgreSQL, etc.)
